Try updating the CMake version to hopefully avoid a missing include of uint32_t
Snippet from GitHub Actions:

11 454.3 In file included from /tmp/cmake/cmake-3.28.1/Utilities/cmcppdap/src/network.cpp:15:
11 454.3 /tmp/cmake/cmake-3.28.1/Utilities/cmcppdap/include/dap/network.h:31:39: error: ‘uint32_t’ has not been declared
11 454.3    31 |                                       uint32_t timeoutMillis = 0);
11 454.3       |                                       ^~~~~~~~
11 454.3 /tmp/cmake/cmake-3.28.1/Utilities/cmcppdap/include/dap/network.h:20:1: note: ‘uint32_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
11 454.3    19 | #include <memory>
11 454.3   +++ |+#include <cstdint>
11 454.3    20 |